# Generated by Django 3.0.6 on 2020-05-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_like_tags', '0002_blog_posts_b_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='fixed_hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hashtags', models.CharField(max_length=2000)),
            ],
        ),
    ]
