# Generated by Django 3.0.6 on 2020-05-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_like_tags', '0003_fixed_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_hashtag',
            name='sub_title',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
