# Generated by Django 3.0.6 on 2020-05-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_like_tags', '0004_fixed_hashtag_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed_hashtag',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
