# Generated by Django 3.0.6 on 2020-05-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_like_tags', '0006_auto_20200531_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_posts',
            old_name='b_url',
            new_name='blogurl',
        ),
        migrations.RenameField(
            model_name='blog_posts',
            old_name='desc',
            new_name='description',
        ),
    ]
